.model flat,c


.code

SSEPackedInt16_Add	PROC
		;PROLOUGE
		PUSH EBP
		MOV  EBP,ESP

		MOV EAX,DWORD PTR[EBP  + 8]
		MOV ECX,DWORD PTR[EBP + 12]
		MOV EDX,DWORD PTR[EBP + 16]

		;MOVDQA -> MEMORY NEED TO ALIGNED IN 16-BYTE BOUNDARY

		MOVDQA XMM0,[EAX]
		MOVDQA XMM1,XMM0
		MOVDQA XMM2,[ECX]

		;ADDITION
		PADDW  XMM0,XMM2				; PACKED ADD - WRAP AROUND
		PADDSW  XMM1,XMM2               ; PACKED ADD - SATURATED

		;SAVE RESULT
		MOVDQA [EDX],XMM0
		MOVDQA [EDX + 16],XMM1

		;EPILOUGE
		LEAVE
		RET
SSEPackedInt16_Add	ENDP

SSEPackedInt32_Sub	PROC

		;PROLOUGE
		PUSH EBP
		MOV EBP,ESP

		MOV EAX,[EBP + 8]
		MOV ECX,[EBP + 12]
		MOV EDX,[EBP + 16]

		;SUBTRACTION
		MOVDQA XMM0,[EAX]
		PSUBD  XMM0,[ECX]

		;MULTIPLICATION
		;MOVDQU -> MEMORY NEED TO BE ALIGNED, IT CAN BE UNALIGNED
		MOVDQU [EDX],XMM0

		;EPILOUGE
		LEAVE
		RET


SSEPackedInt32_Sub	ENDP

SSEPackedInt32_Mul	PROC

		;PROLOUGE
		PUSH EBP
		MOV EBP,ESP

		MOV EAX,[EBP + 8]
		MOV ECX,[EBP + 12]
		MOV EDX,[EBP + 16]

		MOVDQA XMM0,[EAX]
		MOVDQA XMM1,[ECX]

		MOVDQA XMM2,XMM0
		PMULLD XMM0,XMM1		;SIGNED DWORD MUL - LOWER 32-BITS

		PMULDQ XMM2,XMM1		;SIGNED DWORD MUL - QWORD RESULT

		MOVDQA [EDX],XMM0
		MOVDQA [EDX + 16],XMM2

		;EPILOUGE
		POP EBP
		RET



SSEPackedInt32_Mul	ENDP

END