.386
.model flat,c


.code
ArrayReverser	PROC
				;PROLOGUE
				PUSH EBP
				MOV EBP,ESP
				PUSH ESI
				PUSH EDI

				XOR EAX,EAX;CHECK FOR INVALID ARRAY SIZE
				
				;LOADING FUNCTION PARAMETERS INTO REGISTERS
				MOV EDI,[EBP + 8]
				MOV ESI,[EBP + 12]
				MOV ECX,[EBP + 16];ARRAY SIZE IS MOVED TO COUNTER REGISTER FOR LOOPING
				TEST ECX,ECX

				LEA ESI,[ESI+ECX*4-4];CALCULATING LAST ELEMENT'S ADDRESS
				PUSHFD
				STD

;LOOPING
@@:				LODSD
				MOV [EDI],EAX
				ADD EDI,4
				DEC ECX ; DECREMENTING COUNTER
				JNZ @B

				POPFD
				MOV EAX,1
				
				;EPILOGUE
				POP EDI
				POP ESI
				POP EBP

				RET
ArrayReverser	ENDP
				END				
