.386
.model flat,c


.code

CalculateSum	PROC
	;PROLOGUE
	PUSH EBP
	MOV  EBP,ESP
	SUB  ESP,12					; ALLOCATE SPACE FOR 3 LOCAL VARIABLES 4-BYTES FOR EACH
	PUSH EBX
	PUSH ESI
	PUSH EDI


	;LOAD ARGUMENTS
	MOV EAX,DWORD PTR[EBP + 8]
	MOV EBX,DWORD PTR[EBP + 12]
	MOV ECX,DWORD PTR[EBP + 16]
	MOV EDX,DWORD PTR[EBP + 20]
	MOV ESI,DWORD PTR[EBP + 24]
	MOV EDI,DWORD PTR[EBP + 28]

	;COMPUTE S1 = A + B + C
	MOV [EBP - 12],EAX
	ADD [EBP - 12],EBX
	ADD [EBP - 12],ECX

	;COMPUTE S1 = A*A + B*B + C*C
	IMUL EAX,EAX
	IMUL EBX,EBX
	IMUL ECX,ECX
	MOV  DWORD PTR[EBP - 8],EAX
	ADD  DWORD PTR[EBP - 8],EBX
	ADD  DWORD PTR[EBP - 8],ECX

	
	;COMPUTE S1 = A*A*A + B*B*B + C*C*C
	IMUL EAX,DWORD PTR[EBP + 8]
	IMUL EBX,DWORD PTR[EBP + 12]
	IMUL ECX,DWORD PTR[EBP + 16]
	MOV  DWORD PTR[EBP - 4],EAX
	ADD  DWORD PTR[EBP - 4],EBX
	ADD  DWORD PTR[EBP - 4],ECX


	;SAVE S1, S2, S3
	MOV  EAX,DWORD PTR[EBP - 12]
	MOV  DWORD PTR[EDX],EAX

	MOV  EAX,DWORD PTR[EBP - 8]
	MOV  DWORD PTR[ESI],EAX

	MOV  EAX,DWORD PTR[EBP - 4]
	MOV  DWORD PTR[EDI],EAX

	;EPILOGUE
	POP EDI
	POP ESI
	POP EBX
	LEAVE
	RET


CalculateSum	ENDP
END