.model flat,c


.code
MMXMultiply	PROC
	;PROLOUGE
	PUSH EBP
	MOV EBP,ESP

	MOVQ MM0,QWORD PTR[EBP + 8]
	MOVQ MM1,QWORD PTR[EBP + 16]

	MOVQ MM2,MM0
	PMULLW MM0,MM1			; MM0 = PRODUCT LOW RESULT
	PMULHUW MM1,MM2          ; MM1 = PRODUCT HIGH RESULT



	MOVQ MM2,MM0			; MM2 = PRODUCT LOW RESULT
	PUNPCKLWD MM0,MM1		; MM0 = LOW DWORD PRODUCT
	PUNPCKHWD MM2,MM1		; MM2 = HIGH DWORD PRODUCT

	MOV EAX,DWORD PTR[EBP + 24]
	MOV EBX,DWORD PTR[EBP + 28]
	MOVQ QWORD PTR[EAX],MM0
	MOVQ QWORD PTR[EBX],MM2


	;EPILOUGE
	LEAVE
	RET


MMXMultiply	ENDP
END