.model flat,c

.const
	 ALIGN 16
	 AbsMaskFloat	DWORD 7FFFFFFFH,0FFFFFFFFH,0FFFFFFFFH,0FFFFFFFFH
	 AbsMaskDouble	QWORD 7FFFFFFFFFFFFFFFH , 0FFFFFFFFFFFFFFFH

.code

SSEArithmeticOperationsFloat	PROC

		;PROLOUGE
		PUSH EBP
		MOV  EBP,ESP

		MOVSS XMM0,REAL4 PTR[EBP + 8]		;XMM0 = A
		MOVSS XMM1,REAL4 PTR[EBP + 12]		;XMM1 = B

		MOV EAX,DWORD PTR[EBP + 16]			;EAX = ARRAY

		;ADDITION
		MOVSS XMM2,XMM0
		ADDSS XMM2,XMM1						;XMM2 = XMM2 + XMM1

		MOVSS REAL4 PTR[EAX],XMM2			;*ARRAY = A + B

		;SUBTRACTION
		MOVSS XMM3,XMM0
		SUBSS XMM3,XMM1						;XMM3 = XMM3 - XMM1

		MOVSS REAL4 PTR[EAX + 4],XMM3

		;MULTIPLICATION
		MOVSS XMM4,XMM0
		MULSS XMM4,XMM1						;XMM4 = XMM4 * XMM1

		MOVSS REAL4 PTR[EAX + 8],XMM4

		;DIVISION
		MOVSS XMM5,XMM0
		DIVSS XMM5,XMM1						;XMM5 = XMM5 / XMM1

		MOVSS REAL4 PTR[EAX + 12],XMM5

		;MINIMUM
		MOVSS XMM6,XMM0
		MINSS XMM6,XMM1						;XMM6 = MIN(XMM6,XMM1)

		MOVSS REAL4 PTR[EAX + 16],XMM6

		;MAXIMUM
		MOVSS XMM7,XMM0
		MAXSS XMM7,XMM1						;XMM7 = MAX(XMM7,XMM1)

		MOVSS REAL4 PTR[EAX + 20],XMM7

		;ABSOLUTE
		ANDPS XMM1,REAL4 PTR[AbsMaskFloat]	;XMM1 = FABS(XMM1)

		MOVSS REAL4 PTR[EAX + 24],XMM1

		;SQUARE ROOT
		SQRTSS XMM0,XMM1					;XMM0 = SQRT(XMM1)

		MOVSS REAL4 PTR[EAX + 28],XMM0

		;EPILOUGE
		LEAVE
		RET

SSEArithmeticOperationsFloat	ENDP

SSEArithmeticOperationsDouble	PROC

		;PROLOUGE
		PUSH EBP
		MOV  EBP,ESP

		MOVSD XMM0,REAL8 PTR[EBP + 8]		;XMM0 = A
		MOVSD XMM1,REAL8 PTR[EBP + 16]		;XMM1 = B

		MOV   EAX,DWORD PTR[EBP + 24]		;EAX = ARRAY

		;ADDITION
		MOVSD XMM2,XMM0
		ADDSD XMM2,XMM1						;XMM2 = XMM2 + XMM1 

		MOVSD REAL8 PTR[EAX],XMM2			;*ARRAY = A + B

		;SUBTRACTION
		MOVSD XMM3,XMM0
		SUBSD XMM3,XMM1						;XMM3 = XMM3 - XMM1

		MOVSD REAL8 PTR[EAX + 8],XMM3

		;MULTIPLICATION
		MOVSD XMM4,XMM0
		MULSD XMM4,XMM1						;XMM4 = XMM4 * XMM1

		MOVSD REAL8 PTR[EAX + 16],XMM4


		;DIVISION
		MOVSD XMM5,XMM0
		DIVSD XMM5,XMM1						;XMM5 = XMM5 / XMM1

		MOVSD REAL8 PTR[EAX + 24],XMM5

		;MINIMUM
		MOVSD XMM6,XMM0
		MINSD XMM6,XMM1						;XMM6 = MIN(XMM6,XMM1)

		MOVSD REAL8 PTR[EAX + 32],XMM6

		;MAXIMUM
		MOVSD XMM7,XMM0
		MAXSD XMM7,XMM1						;XMM7 = MAX(XMM7,XMM1)

		MOVSD REAL8 PTR[EAX + 40],XMM7

		;ABSOLUTE
		ANDPD XMM1,REAL8 PTR[AbsMaskDouble]	;XMM1 = FABS(XMM1)

		MOVSD REAL8 PTR[EAX + 48],XMM1

		;SQUARE ROOT
		SQRTSD XMM0,XMM1					;XMM0 = SQRT(XMM1)

		MOVSD REAL8 PTR[EAX + 56],XMM0

		;EPILOUGE
		LEAVE
		RET

SSEArithmeticOperationsDouble	ENDP

END
