.model flat, c

;SCALAR DOUBLE PRECISION FLOATING POINT ARITHMETIC

.const 
	;Mask
	AbsMask QWORD 7FFFFFFFFFFFFFFFH, 0FFFFFFFFFFFFFFFH

.code

AVX_fp_Arithmetic	PROC

		;PROLOUGE
		PUSH EBP
		MOV EBP,ESP

		MOV EAX,DWORD PTR[EBP + 24]

		; AVX SCALAR DOBULE PRECISION MOV
		; IT WAS SAME TO MOVSD BUT IT SETS ALL HIGHER 192-BITS TO ZERO
		;ONLY LOWER 64-BITS ARE UTILIZED

		VMOVSD XMM0, REAL8 PTR[EBP + 8]
		VMOVSD XMM1, REAL8 PTR[EBP + 16]

		;THREE OPERAND FORM

		;ADDITION
		VADDSD XMM2,XMM0,XMM1		;XMM2 = XMM0 + XMM1
		;SUBTRACTION
		VSUBSD XMM3,XMM0,XMM1		;XMM3 = XMM0 - XMM1
		;MULTIPLICATION
		VMULSD XMM4,XMM0,XMM1		;XMM4 = XMM0 * XMM1
		;DIVISION
		VDIVSD XMM5,XMM0,XMM1       ;XMM5 = XMM0 / XMM1

		VMOVSD REAL8 PTR[EAX],XMM2
		VMOVSD REAL8 PTR[EAX + 8],XMM3
		VMOVSD REAL8 PTR[EAX + 16],XMM4
		VMOVSD REAL8 PTR[EAX + 24],XMM5

		;MINIMUM
		VMINSD XMM2,XMM0,XMM1						;XMM2 = MIN(XMM0,XMM1)
		;MAXIMUM
		VMAXSD XMM3,XMM0,XMM1						;XMM3 = MAX(XMM0,XMM1)
		;SQUARE ROOT
		VSQRTSD XMM4,XMM0,XMM0						;XMM4 = SQRT(XMM0)

		;ABSOLUTE
		VANDPD  XMM5,XMM1,XMMWORD PTR[AbsMask]	    ;XMM5 = ABS(XMM1)

		VMOVSD REAL8 PTR[EAX + 32],XMM2
		VMOVSD REAL8 PTR[EAX + 40],XMM3
		VMOVSD REAL8 PTR[EAX + 48],XMM4
		VMOVSD REAL8 PTR[EAX + 56],XMM5
		
		;EPILOUGE
		LEAVE
		RET

AVX_fp_Arithmetic	ENDP

END