.model flat,c

.const
	DegToRad		REAL8		0.017453229252
	RadToDeg		REAL8		57.2957795131



.code

; RECTANGULAR TO POLAR NOTATION CONVERTOR
RectToPolar		PROC
	;PROLOUGE
	PUSH EBP
	MOV EBP,ESP

	FLD REAL8 PTR[EBP + 16]
	FLD REAL8 PTR[EBP + 8]

	FPATAN							; CALC atan2 (y / x)
	FMUL RadToDeg

	MOV  EAX,DWORD PTR[EBP + 28]
	FSTP REAL8 PTR[EAX]				; A = ARC_TANGENT

	FLD REAL8 PTR[EBP + 8]
	FMUL ST(0),ST(0)				;ST(0) =  X^2
	FLD REAL8 PTR[EBP + 16]			
	FMUL ST(0),ST(0)				;ST(0) = Y^2,ST(1) =  X^2

	FADDP							; ST(0) = X^2 + Y^2

	FSQRT							; SQRT(ST(0))

	MOV EAX,DWORD PTR[EBP + 24]
	FSTP REAL8 PTR[EAX]

	;EPILOUGE
	LEAVE
	RET

RectToPolar		ENDP

; POLAR TO RECTANGULAR NOTATION CONVERTOR
PolarToRect		PROC
	;PROLOUGE
	PUSH EBP
	MOV EBP,ESP

	FLD REAL8 PTR[EBP + 16]
	FMUL DegToRad

	FSINCOS							; CALC SIN(ST(0)) AND COS(ST(0)) STORE IT IN ST(1) AND ST(0)
	FMUL REAL8 PTR[EBP + 8]			; ST(0) (X) = R * COS(A), ST(1) = SIN(A)

	MOV  EAX,DWORD PTR[EBP + 24]
	FSTP REAL8 PTR[EAX]

	FMUL REAL8 PTR[EBP + 8]			; ST(0) (Y)= R * SIN(A)
	
	MOV  EAX,DWORD PTR[EBP + 28]
	FSTP REAL8 PTR[EAX]

	;EPILOUGE
	LEAVE
	RET

PolarToRect		ENDP

END