.model flat,c


.code

CalcMeanStdev	PROC
	;PROLOUGE
	PUSH EBP
	MOV  EBP,ESP
	
	SUB  ESP,4				;LOCAL FOR (N- 1) STANDARD DEVIATION

	XOR EAX,EAX

	MOV ECX,DWORD PTR[EBP + 12]		
	CMP ECX,1				
	JLE Done
	DEC ECX

	MOV DWORD PTR[EBP - 4],ECX		;(N- 1) FOR STANDARD DEVIATION 

	INC ECX					

	MOV EDX,DWORD PTR[EBP + 8]	

	FLDZ							;ST(0) = 0.0

@@:
	FADD REAL8 PTR[EDX]
	ADD EDX,8
	DEC ECX
	JNZ @B

	FIDIV DWORD PTR[EBP + 12]
	 
	
	MOV EDX,DWORD PTR[EBP + 8]
	MOV ECX,DWORD PTR[EBP + 12]
	FLDZ							; ST(0) = 0.0 , ST(1) = MEAN


@@:
	FLD REAL8 PTR[EDX]				; ST(0) = *ARRAY , ST(1) = 0.0 , ST(2) = MEAN
	FSUB ST(0),ST(2)				; ST(0) = *ARRAY - MEAN, ST(1) = 0.0 , ST(2) = MEAN
	FMUL ST(0),ST(0)				; ST(0) = (*ARRAY - MEAN)^2, ST(1) = 0.0 , ST(2) = MEAN
	FADDP
	ADD EDX,8
	DEC ECX
	JNZ @B

	FIDIV DWORD PTR[EBP - 4]
	FSQRT							; TAKE SQRT IN ST(0)

	MOV   EAX,DWORD PTR[EBP + 20]
	FSTP  REAL8 PTR[EAX]			;*STANDARD_DEVIATION = SQRT(SUMMATION(X-MEAN)^2/N-1)
	MOV   EAX,DWORD PTR[EBP + 16]
	FSTP  REAL8 PTR[EAX]			;*MEAN = SUM/N

	MOV EAX,1						;SUCCESS
Done:
	;EPILOUGE

	LEAVE
	RET

CalcMeanStdev	ENDP
END