.model flat,c


.code
AVXPackedInt_16	PROC

	;PROLOUGE
	PUSH EBP
	MOV EBP,ESP

	MOV EAX,DWORD PTR[EBP + 8]
	MOV ECX, DWORD PTR[EBP + 12]
	MOV EDX, DWORD PTR[EBP + 16]

	; ALIGNED MOV
	VMOVDQA YMM0,YMMWORD PTR[EAX]
	VMOVDQA YMM1,YMMWORD PTR[ECX]

	VPADDW  YMM2,YMM0,YMM1    ;YMM2  = YMM0 + YMM1 (WRAP AROUND)
	VPADDSW YMM3,YMM0,YMM1	  ;YMM3  = YMM0 + YMM1 (SATURATED)

	VPSUBW	YMM4,YMM0,YMM1	  ;YMM4  = YMM0 - YMM1 (WRAP AROUND)
	VPSUBSW YMM5,YMM0,YMM1	  ;YMM5  = YMM0 - YMM1 (SATURATED)

	VPMINSW YMM6,YMM0,YMM1	  ;YMM6 = MIN(YMM0,YMM1) (SIGNED)
	VPMAXSW YMM7,YMM0,YMM1	  ;YMM7 = MAX(YMM0,YMM1) (SIGNED) 

	VMOVDQA YMMWORD PTR[EDX],YMM2
	VMOVDQA YMMWORD PTR[EDX + 32],YMM3
	VMOVDQA YMMWORD PTR[EDX + 64],YMM4
	VMOVDQA YMMWORD PTR[EDX + 96],YMM5
	VMOVDQA YMMWORD PTR[EDX + 128],YMM6
	VMOVDQA YMMWORD PTR[EDX + 160],YMM7

	VZEROUPPER				; THIS SAVE THE TRANSITION PENALTIES FROM AVX TO SSE, IN TRANSITION FROM AVX TO SSE THE PROCESSOR TRIES TO SAVE THE STATE OF UPPER 128-BITS WHICH CAUSE TRANSITION PENALITIES , WHICH CAN BE AVOIDED BY MAKING ZERO THE UPPER 128-BITS OF ALL YMM REGISTERS BEFORE MOVING INTO SSE

	LEAVE
	RET


AVXPackedInt_16	ENDP

AVXPackedInt_32	PROC

	;PROLOUGE
	PUSH EBP
	MOV EBP,ESP

	MOV EAX,DWORD PTR[EBP + 8]
	MOV ECX, DWORD PTR[EBP + 12]
	MOV EDX, DWORD PTR[EBP + 16]

	VMOVDQA YMM0,YMMWORD PTR[EAX]
	VMOVDQA YMM1,YMMWORD PTR[ECX]

	VPHADDD	YMM2,YMM0,YMM1			;YMM2 = HORIZONTAL ADDITION
	VPHSUBD YMM3,YMM0,YMM1			;YMM3 = HORIZONTAL SUBTRACTION
	VPMULLD YMM4,YMM0,YMM1			;YMM4 = YMM0 * YMM1 (DWORD) MULTIPLICATION
	VPSLLVD YMM5,YMM0,YMM1			;YMM5 = YMM0 << YMM1 (DWORD) LOGICAL LEFT SHIFT (SHIFT COUNT GREATER THAN 32 ARE ZERO)	
	VPSRAVD YMM6,YMM0,YMM1			;YMM6 = YMM0 >> YMM1 (DWORD) ARITHMETIC RIGHT SHIFT (SHIFT COUNT GREATER THAN 32 ARE MINUS ONE IN ARITHMETIC AND ZERO IN LOGICAL)

	VMOVDQA YMMWORD PTR[EDX],YMM2
	VMOVDQA YMMWORD PTR[EDX + 32],YMM3
	VMOVDQA YMMWORD PTR[EDX + 64],YMM4
	VMOVDQA YMMWORD PTR[EDX + 96],YMM5
	VMOVDQA YMMWORD PTR[EDX + 128],YMM6

	VZEROUPPER

	LEAVE
	RET

AVXPackedInt_32	ENDP

END